name: Deploy
on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test and build
        run: |
          npm ci
          npm run build
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist